library(dplyr)
us1<-read.csv("USecon.csv")
attach(us1)
sub.west <-subset(us1, WEST=="1")
sub.westsort<-arrange(sub.west, ECAB)
t.test(ECAB~WEST)
cor(GROW, ECAB)
ggplot(us1, aes(x=GROW, y=ECAB,color = WEST))+geom_point()
m1<-lm(ECAB~EX)
m2<-lm(ECAB~YOUNG)
summary(m1)
summary(m2)
